### ISSUE TITLE
'System.NullReferenceException' occurred in Ci.Sort.dll while sorting

### ISSUE THREAD

**Issue by bbenetskyy** [lettucebo/Ci.Sort#1] opened 2018-03-14 14:30 UTC
Hi,

Thanks for helpfull library.  All is cool, but when I'm try to sort class which have property another one class, I'm always get an excption.

I'm attach here file for reproducing this bag or this feature. 

Please help me resolve it. Or let me know how modify attached solution for work with such data.

Thank you a lot)))

[Program.txt](https://github.com/lettucebo/Ci.Sort/files/1811514/Program.txt)

**Comment by lettucebo** [comment] 2018-03-15 07:58
Hi

I have run your sample program

find out that the issue is class Car doesn't have Name property

And the this library original doesn't consider about the child property sort

This is library main idea is to help aspnet mvc table with sort functionality

Maybe you have a better idea for this situation?

**Comment by bbenetskyy** [comment] 2018-03-15 08:28
I will look for solution on this weekend and let you know if I will found it.

But thanks for clarify for what originaly is this library. 

I'm used it with ASP.NET WebApi project, for possibility to sort data from any user request with different view models.
And I want to add possiblity for end user sort by any of view model parameters, and make it dynamically in one helper class.

**Comment by lettucebo** [comment] 2018-03-22 04:11
Fixed By #2

**Closed as completed by lettucebo** 2018-03-22 04:11 UTC
